<?php
    $myStatus = $this->isCustomerLoggedIn();
    $data = $this->data();
        $fullname = $data['fullname'];
        $firstname = $data['firstname'];
        $lastname = $data['lastname'];
        $region_select = $this->escapeHtml($this->getAddress()->getRegion());
        $taxvat = $data['taxvat'];
        $exibe_email = $data['exibe_email'];
        $_dob = $this->getLayout()->createBlock('customer/widget_dob');
        $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat');
        $_gender = $this->getLayout()->createBlock('customer/widget_gender');
        if(Mage::getStoreConfig('onestepcheckout/layout/page_layout')==5){
            if(!$myStatus){
                $force_division = "span6 grid12-6";
                $tyle="border-right:1px solid;width: 47%;";

            } else {
                $force_division = "";
                $tyle="";
            }

        } else {
            $force_division = "";
            $tyle="";
        }
?>
        <fieldset>
            <ul class="form-list" id="moip_onstepcheckout_billing_form" >
            <?php if(!$myStatus):?>
                        <?php if(Mage::getStoreConfig('onestepcheckout/layout/enable_quicklogin') && !$force_division):?>
                                    <a id="loginbox" href="#" data-toggle="modal" data-target="#loginModel"  title="Entrar com a sua conta"><?php echo $this->__('Already registered? Click here to login.');?></a>
                        <?php endif?>
                    <?php endif?>
                    <input type="hidden" title="Permanecer logado" name="form_key" value="<? echo Mage::getSingleton('core/session')->getFormKey(); ?>" class="input-hidden" />
                <input type="hidden" name="billing[address_id]" title="Endereço selecionado"  value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id"class="input-hidden"  />
<div class="<?php echo $force_division ?>" style="<?php echo $tyle; ?>">
<?php if($force_division): ?><h3>Meu Cadastro</h3><?php endif; ?>
<li class="fields">
    <div class="customer-name field">
        <label for="billing:firstname" class="required"><em>*</em>Nome</label>
        <div class="input-box">
            <input  autocomplete="off" type="text" id="billing:firstname" name="billing[firstname]" value="<?php echo  $firstname; ?>" title="Nome" class="input-text required-entry" placeholder="Nome">
        </div>
    </div>
    <div class="field name-lastname">
        <label for="billing:lastname" class="required"><em>*</em>Sobrenome</label>
        <div class="input-box">
            <input  autocomplete="off" type="text" id="billing:lastname" name="billing[lastname]" value="<?php echo  $lastname; ?>" title="Sobrenome" class="input-text required-entry"  placeholder="Sobrenome">
        </div>
    </div>
</li>
<?php if($exibe_email != 0): ?>
<li class="wide">
    <label for="billing:email" class="required"><em>*</em>Endereço de e-mail</label>
    <div class="input-box">
        <input  autocomplete="off" type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape( Mage::getSingleton('customer/session')->getCustomer()->getEmail()) ?>" <?php if($myStatus) echo 'readonly="true"';  ?> title="Endereço de e-mail" class="input-text validate-email required-entry"  placeholder="Email">
    </div>
</li>
<?php else: ?>
    <input  autocomplete="off" type="hidden" name="billing[email]"  value="<?php echo $this->htmlEscape( Mage::getSingleton('customer/session')->getCustomer()->getEmail()) ?>"  id="email" class="input-hidden">

<?php endif; ?>
<?php if(!$myStatus): ?>
<li class="fields" id="register-customer-password" style="display:block;">
    <div class="field">
        <label for="billing:customer_password" class="required"><em>*</em>Crie sua Senha</label>
        <div class="input-box">
            <input  autocomplete="off" type="password" name="billing[customer_password]" id="billing:customer_password" title="Senha" class="input-text required-entry validate-password"  placeholder="Senha">
        </div>
    </div>
    <div class="field">
        <label for="billing:confirm_password" class="required"><em>*</em>Confirmar sua Senha</label>
        <div class="input-box">
            <input  autocomplete="off" type="password" name="billing[confirm_password]" onkeypress="valide_senha(this);" title="Confirmar senha" id="billing:confirm_password" class="input-text required-entry validate-cpassword" placeholder="Confirmar Senha">
        </div>
    </div>
</li>
    <input  autocomplete="off" type="hidden" name="billing[register_new_account]" value="1" title="Criar conta" id="register_new_account" class="input-hidden">
     <input  autocomplete="off" type="hidden" name="billing[persistent_remember_me]" value="1" title="Continuar logado" id="persistent_remember_me" class="input-hidden">


<p style="padding-bottom:10px;">A senha criada será utilizada para você ter acesso futuro a loja e acompanhar o seu pedido.</p>

<?php endif; ?>
<?php if(Mage::getStoreConfig('onestepcheckout/config/enable_pj')):?>


<li class="fields pj-pf">
    <div class="field">
            <label class="">
                <input  autocomplete="off" type="radio" name="billing[tipopessoa]" class="radio validate-one-required-by-name"  value="1" id="billing:pf" onclick="getval(this);" checked>
                Pessoa Física
            </label>
    </div>
    <div class="field">
        <label  class="">
            <input  autocomplete="off" type="radio" name="billing[tipopessoa]"  class="radio validate-one-required-by-name" value="2" id="billing:pj" onclick="getval(this);">
            Pessoa Jurídica
        </label>
    </div>
</li>
<li class="fields dados-pj">
    <div class="field">
        <label for="billing:nomefantasia" class="required"><em>*</em>Nome Fantasia</label>
        <div class="input-box">
            <input  autocomplete="off" type="text" title="Nome Fantasia" class="input-text" name="billing[nomefantasia]" id="nomefantasia" value="<?php echo $this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getNomefantasia()); ?>"  placeholder="Nome Fantasia">
        </div>
    </div>
    <div class="field">
        <label for="billing:razaosocial" class="required"><em>*</em>Razão Social</label>
        <div class="input-box">
            <input  autocomplete="off" type="text" title="razao_social" class="input-text" name="billing[razaosocial]" id="razaosocial" value="<?php echo $this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getRazaosocial()) ?>" placeholder="Razão Solcial" >
        </div>
    </div>
</li>
<li class="fields dados-pj">
    <div class="field">
        <label for="billing:cnpj" class="required"><em>*</em>CNPJ</label>
        <div class="input-box">
            <input  autocomplete="off" type="text" title="cnpj" class="input-text" name="billing[cnpj]" id="cnpj" value="<?php echo $this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getCnpj()) ?>"  placeholder="CNPJ">
        </div>
    </div>
    <div class="field">
        <label for="billing:insestadual" class="required"><em>*</em>Inscrição Estadual</label>
        <div class="input-box">
            <input  autocomplete="off" type="text" title="Inscrição Estadual" class="input-text" name="billing[insestadual]"   value="<?php echo $this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getInsestadual()) ?>" id="insestadual" value="" placeholder="Inscrição Social">
        </div>
        <input  autocomplete="off" type="checkbox" name="Isento" title="Isento para a Inscrição Estadual" onclick="marcar_isento()" style="width: 15px !important;"><label>Isento</label>
    </div>
</li>

<?php endif; ?>
<li class="fields">
    <?php if ($_taxvat->isEnabled()): ?>
        <div class="field">
            <label for="billing:taxvat" class="required"><em>*</em>CPF </label>
            <div class="input-box">
                <input  autocomplete="off" type="text" id="billing:taxvat" name="billing[taxvat]"value="<?php echo $taxvat;?>"  title="CPF" class="input-text required-entry"  placeholder="CPF">
            </div>
            <script  type="text/javascript">
            //<![CDATA[
                $('billing:taxvat').addClassName('validar_cpf');
                Validation.add('validar_cpf', 'O CPF informado \xE9 invalido', function(v){return validaCPF(v,0);});
            //]]>
            </script>
        </div>
    <?php endif; ?>
    <div class="field">
        <label for="billing:telephone" class="required"><em>*</em>Telefone</label>
        <div class="input-box">
            <input  autocomplete="off" type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>"  title="Telefone" class="input-text validate-tel-national required-entry" id="billing:telephone"  placeholder="Telefone">
            <script type="text/javascript">
            //<![CDATA[
                Validation.add('validate-tel-national', 'Entre com telefone válido: (99)9999-?9999', function(v) {
                    return Validation.get('IsEmpty').test(v) || /^([()])([0-9]){2}([)])([0-9]){4}([-])([0-9]){4,5}$/.test(v);
                });
            //]]>
            </script>
        </div>
    </div>
</li>
<li class="fields">
    <?php if ($_dob->isEnabled()): ?>
        <div class="field">
            <?php echo $this->getLayout()->createBlock('customer/widget_dob')
               ->setDate($this->getCustomer()->getDob())
               ->setFieldIdFormat('billing:%s')
               ->setFieldNameFormat('billing[%s]')
               ->toHtml() ?>
        </div>
    <?php endif ?>
    <?php if ($_gender->isEnabled()): ?>
        <div class="field">
        <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml(); ?>
        </div>
    <?php endif ?>
</li>
</div>
<div class="<?php echo $force_division ?>">
<?php if($force_division): ?><h3>Meu Endereço</h3><?php endif; ?>
<li class="fields">
    <div class="field">

        <label for="billing:postcode" class="required"><em>*</em>CEP</label>
        <div class="input-box">
            <input  autocomplete="off" type="text" title="CEP" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>"  class="input-text validate-zip-international  required-entry moipzip" onchange="javascript: buscarEndereco('billing');"    style="width: 100px;" placeholder="CEP">
        </div>
        <script  type="text/javascript">
    //<![CDATA[
        Validation.add('validate-zip-international', 'Entre com um cep válido: 99999-999', function(v) {
            return Validation.get('IsEmpty').test(v) || /^([0-9]){5}([-])([0-9]){3}$/.test(v);
        });
    //]]>
    </script>
    </div>
    <div class="field">
        <div class="input-box" style="margin-top: 20px;margin-bottom: 8px;">
                <a href="http://www.buscacep.correios.com.br/" target="_blank">Não sabe o CEP?</a>
        </div>
    </div>
</li>
<li class="wide">
    <label for="billing:street1" class="required"><em>*</em>Endereço</label>
    <div class="input-box">
        <input  autocomplete="off" type="text" title="Endereço da rua" name="billing[street][0]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text  required-entry" placeholder="Endereço">
    </div>
</li>
<li class="fields">
    <div class="field">
        <label for="billing:street2" class="required"><em>*</em>Número</label>
        <div class="input-box">
            <input  autocomplete="off" type="text" title="Número" name="billing[street][1]" id="billing:street2" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" class="input-text  required-entry" placeholder="Número">
        </div>
    </div>
    <div class="field">
        <label for="billing:street3" class="required">Complemento</label>
        <div class="input-box">
            <input  autocomplete="off" type="text" title="Complemento" name="billing[street][2]" id="billing:street3" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(3)) ?>" class="input-text" placeholder="Complemento">
        </div>
    </div>
</li>



<li class="fields">
    <div class="field">
        <label for="billing:street4" class="required"><em>*</em>Bairro</label>
        <div class="input-box">
            <input  autocomplete="off" type="text" title="Bairro" name="billing[street][3]" id="billing:street4" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(4)) ?>" class="input-text required-entry" placeholder="Bairro">
        </div>
    </div>
    <div class="field">
        <label for="billing:city" class="required"><em>*</em>Cidade</label>
        <div class="input-box">
            <input  autocomplete="off" type="text" title="Cidade" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>"class="input-text  required-entry" id="billing:city" placeholder="Cidade">
        </div>
    </div>
</li>
<li class="fields">
    <div class="field">
        <label for="billing:region_id" class=""><em>*</em>Estado</label>
        <div class="input-box">
            <select id="billing:region_id" name="billing[region_id]" title="Estado" style="display: none;" defaultvalue="" class="validate-select">
                <option value="">Por favor, selecione o estado</option>
            </select>
            <script  type="text/javascript">//<![CDATA[
                    $("billing:region_id").setAttribute("defaultValue",  "");
            //]]></script>
            <input  autocomplete="off" type="text" maxlength="2" id="billing:region" name="billing[region]"  value="<?php echo $region_select ?>"  title="Estado" class="input-text" style="" >
        </div>
    </div>

    <div class="field">
            <label for="billing:country_id" class="required"><em></em>País</label>
            <div class="input-box">
                 <?php echo $this->getCountryHtmlSelect('billing') ?>
            </div>
    </div>
</li>
<?php if($force_division): ?>
<div class="buttons-set">
                                    <button type="submit"  onclick="createAccount();" title="Prosseguir" class="button btn-button"><span><span>Prosseguir</span></span></button>
                         </div>
<?php endif; ?>
</div>


                                <li  class="control">
                                    <?php if(Mage::getStoreConfig('onestepcheckout/config/allowshippingotheraddress')):?>

                                            <?php if(!Mage::helper('onestepcheckout')->onlyProductDownloadable()):?>
                                                <?php if(!$force_division): ?>
                                                    <a class="btn button" id="ship_to_same_address"  onclick="jQuery('#billing\\:ship_to_same_address').val('0');">Enviar Para Outro Endereço</a>
                                                    <input type="hidden" name="ship_to_same_address"  value="1" title="<?php echo $this->__('ship to same address') ?>" id="billing:ship_to_same_address" class="checkbox" checked="checked"  >
                                                <?php endif; ?>
                                            <?php else:?>
                                                <?php if(!$force_division): ?>
                                                <input type="hidden" name="ship_to_same_address"  value="1" title="<?php echo $this->__('ship to same address') ?>">
                                                <?php endif; ?>
                                            <?php endif; ?>

                                    <?php else:?>
                                            <?php if(!$force_division): ?>
                                                <input type="hidden" name="ship_to_same_address"  value="1" title="<?php echo $this->__('ship to same address') ?>">
                                            <?php endif; ?>
                                    <?php endif; ?>
                                </li>

                                <li  class="control">
                                    <?php if ($myStatus):?>

                                            <input type="checkbox" name="save_in_address_book" <?php if (!Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()):?>   value="1" <?php else: ?> value='0' <?php endif; ?>onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if (!Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()):?> checked="checked"<?php endif;?>  title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" class="checkbox" />
                                            <label for="billing:save_in_address_book" ><?php echo $this->__('Salvar como novo endereço') ?></label>
                                    <?php else : ?>
                                            <input type="hidden" name="billing[save_in_address_book]" value="1" />
                                            <input type="hidden" name="billing[address_id]"  value=""/>
                                    <?php endif; ?>
                                </li>

            </ul>
        </fieldset>
<script  type="text/javascript">
//<![CDATA[
    jQuery(function(){jQuery("#billing-new-address-form").show();});
    var billing = new Billing("co-billing-form","<?php echo $this->getUrl('checkout/onepage/getAddress/address/') ?>", "<?php echo $this->getUrl('checkout/onepage/saveBilling/') ?>");
    var billingForm = new VarienForm("co-billing-form");
    var billingRegionUpdater = new RegionUpdater("billing:country_id", "billing:region", "billing:region_id", countryRegions, undefined, "billing:postcode");
//]]>
</script>